version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: sqlcompat-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: sqlcompat
      POSTGRES_USER: sqlcompat
      POSTGRES_PASSWORD: sqlcompat
    ports:
      - "5433:5432"
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
